// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const prismaCliDatabaseUrl =
  process.env['DIRECT_DATABASE_URL'] ||
  process.env['DIRECT_URL'] ||
  process.env['DATABASE_URL'];

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: prismaCliDatabaseUrl,
  },
});
